const CONFIG = {
    titleWeb: "Hiii:Đ",
    introTitle: 'Làm theo như con Vyy thôi=)',
    introDesc: `Nụ cười của Super Idol Cũng không ngọt như cậu Cái nắng chói chang giữa tháng 8 Cũng không tỏa nắng bằng cậu =))`,
    btnIntro: 'Con Vyy dạy mình đấy=)',
    title: 'Bạn có quý con Lạcc (loài) dù nó ngu méo tả nổi này không=))',
    desc: 'Chọn đi bạn:)) ',
    btnYes: 'Dell bạn ạ<3',
    btnNo: 'Kó bạn ặ:3',
    question: 'Ựa sao bạn ghét mình:(',
    btnReply: 'Ựa sảd :(',
    reply: 'Vì bạn ngu ẻ ai thèm quý, rồi còn biếng gánh gãy lưng',
    mess: 'Hmu éo crush bạn nữa, giãy đành đành🙀💔',
    messDesc: 'Thế bạn muốn gánh mình thêm Toán Anh Văn với gánh mình như gánh tạ tiếp ko=))',
    btnAccept: 'Méo bạn, mệt rồi',
    messLink: 'https://genshin.mihoyo.com/vi/home'
